<a href="https://colab.research.google.com/github/mahananda123/MahanandaReddy/blob/main/DummyDataSet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Let's test your knowledge about Python, data structures, NumPy, and pandas.
We are going to createa a dummy dataset for some Youtubers regarding their channals. We will create data including:
1. Decide the size of the dataset by using a SIZE constant variable
2. ChannelID ( Y0001 , Y0002 , ...)
3. Number of subscribers
4. Number of videos
5. Number of total views
6. Category ( ['music','news','gaming','food','travel'] )
7. Language ( ['English','Spanish','Japanese','Franch','Russia','Chinese'] )
8. Type( ['Corperate','Goverment','NGO','Individual'] )

Then we will play with the dummy dataset with our knowledge of pandas, including:
1. Access
2. Sampling
3. Filtering
4. Aggregation
5. Manipulation

In [2]:
import numpy as np
import pandas as pd
import random

In [3]:
SIZE=1000

In [4]:
ids=['Y{0:04d}'.format(x) for x in range(SIZE)]
ids[:5],ids[-5:]

(['Y0000', 'Y0001', 'Y0002', 'Y0003', 'Y0004'],
 ['Y0995', 'Y0996', 'Y0997', 'Y0998', 'Y0999'])

In [5]:
subs=np.random.normal(100000,50000,(SIZE))
subs[:5],subs[-5:]

(array([120494.81646358,  94610.9164659 , 193049.14562729,  85512.0073179 ,
        158689.26837643]),
 array([ 45449.15264165,  77556.52063771,  65648.76569793, 139267.20448121,
        169977.01388578]))

In [6]:
subs=subs.astype(int)
subs[:5]

array([120494,  94610, 193049,  85512, 158689])

In [7]:
subs[subs<=0]

array([-21486, -44172, -15442, -21888, -10765,   -756,  -3946, -25683,
       -16721,  -8599, -13184,  -2641,  -9672,  -4729, -10693,  -1899,
       -16973, -37045, -10439, -11597])

In [8]:
subs[subs<=0]=1
subs[subs<=0]

array([], dtype=int64)

In [9]:
nvideos=np.random.randint(1,200,SIZE)
nvideos[:5],nvideos[-5:]

(array([71, 91, 23,  9, 12]), array([ 98,  56, 139,  36,  13]))

In [10]:
views=[int(x*1.5*np.random.random()+y*2*np.random.random()) for x,y in zip(subs,nvideos)]
views[:5]

[111, 90663, 222465, 86226, 23830]

In [11]:
views=np.array(views)
views[:5]

array([   111,  90663, 222465,  86226,  23830])

In [12]:
views[views<0]=0

In [13]:
category=np.random.choice(['music','news','gaming','food','travel'],SIZE)
category[:20]

array(['food', 'news', 'food', 'news', 'news', 'news', 'news', 'music',
       'gaming', 'news', 'music', 'news', 'travel', 'news', 'news',
       'food', 'gaming', 'news', 'gaming', 'music'], dtype='<U6')

In [14]:
language=np.random.choice(['English','Spanish','Japanese','Franch','Russia','Chinese'],SIZE, p=[0.5, 0.1, 0.1, 0.1, 0.1, 0.1])
language[:20]

array(['Chinese', 'Japanese', 'Chinese', 'Chinese', 'Franch', 'English',
       'English', 'English', 'Chinese', 'English', 'Franch', 'Franch',
       'Japanese', 'English', 'Chinese', 'English', 'English', 'English',
       'English', 'Russia'], dtype='<U8')

In [15]:
typ=np.random.choice(['Corperate','Goverment','NGO','Individual'],SIZE, p=[0.1, 0.2, 0.3, 0.4])
typ[:20]

array(['Goverment', 'Individual', 'Goverment', 'NGO', 'Individual', 'NGO',
       'Individual', 'NGO', 'NGO', 'Individual', 'Goverment',
       'Individual', 'Individual', 'Individual', 'Goverment', 'Goverment',
       'NGO', 'NGO', 'Individual', 'Individual'], dtype='<U10')

In [16]:
df=pd.DataFrame({'ChannelID': ids,
                   'subs': subs,
                   'nvideos': nvideos,
                   'views': views,
                   'Category': category,
                   'Language':language,
                   'Type': typ},
                index=np.arange(1,SIZE+1))
df.head()

ChannelID    subs  nvideos   views Category  Language        Type
1     Y0000  120494       71     111     food   Chinese   Goverment
2     Y0001   94610       91   90663     news  Japanese  Individual
3     Y0002  193049       23  222465     food   Chinese   Goverment
4     Y0003   85512        9   86226     news   Chinese         NGO
5     Y0004  158689       12   23830     news    Franch  Individual

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 1 to 1000
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   ChannelID  1000 non-null   object
 1   subs       1000 non-null   int64 
 2   nvideos    1000 non-null   int64 
 3   views      1000 non-null   int64 
 4   Category   1000 non-null   object
 5   Language   1000 non-null   object
 6   Type       1000 non-null   object
dtypes: int64(3), object(4)
memory usage: 62.5+ KB


In [18]:
df.to_csv('YT.csv',index=False)

In [19]:
df_sub1=df.loc[:100]
df_sub1

ChannelID    subs  nvideos   views Category  Language        Type
1       Y0000  120494       71     111     food   Chinese   Goverment
2       Y0001   94610       91   90663     news  Japanese  Individual
3       Y0002  193049       23  222465     food   Chinese   Goverment
4       Y0003   85512        9   86226     news   Chinese         NGO
5       Y0004  158689       12   23830     news    Franch  Individual
..        ...     ...      ...     ...      ...       ...         ...
96      Y0095  135842      118   22199     news    Franch   Goverment
97      Y0096   52872      108    2216    music  Japanese         NGO
98      Y0097   85159      102   59675     food   English  Individual
99      Y0098  104736        3   99497   travel   Chinese         NGO
100     Y0099  151204       72  152847     news    Franch   Goverment

[100 rows x 7 columns]

In [20]:
df1=pd.read_csv('YT.csv')

In [21]:
df1.head()

ChannelID    subs  nvideos   views Category  Language        Type
0     Y0000  120494       71     111     food   Chinese   Goverment
1     Y0001   94610       91   90663     news  Japanese  Individual
2     Y0002  193049       23  222465     food   Chinese   Goverment
3     Y0003   85512        9   86226     news   Chinese         NGO
4     Y0004  158689       12   23830     news    Franch  Individual

In [22]:
df1.head(10)

ChannelID    subs  nvideos   views Category  Language        Type
0     Y0000  120494       71     111     food   Chinese   Goverment
1     Y0001   94610       91   90663     news  Japanese  Individual
2     Y0002  193049       23  222465     food   Chinese   Goverment
3     Y0003   85512        9   86226     news   Chinese         NGO
4     Y0004  158689       12   23830     news    Franch  Individual
5     Y0005  152856       12    8548     news   English         NGO
6     Y0006   36372       65   28139     news   English  Individual
7     Y0007  131259      130  196058    music   English         NGO
8     Y0008  137299       86    8745   gaming   Chinese         NGO
9     Y0009   98378       25  124120     news   English  Individual

In [23]:
df1.tail()

ChannelID    subs  nvideos   views Category Language        Type
995     Y0995   45449       98   63153   gaming  English  Individual
996     Y0996   77556       56   59019    music  English  Individual
997     Y0997   65648      139   66299    music  English   Goverment
998     Y0998  139267       36  125546     news  English   Goverment
999     Y0999  169977       13   27183   gaming   Russia  Individual

In [24]:
df1.tail(10)

ChannelID    subs  nvideos   views Category Language        Type
990     Y0990  110382      161   79838    music  Chinese         NGO
991     Y0991   62835       88   67758    music  English         NGO
992     Y0992   39065       46   52219   travel  English         NGO
993     Y0993  132616      150  183207     news  English   Goverment
994     Y0994  182512        9   76605   travel  Spanish   Corperate
995     Y0995   45449       98   63153   gaming  English  Individual
996     Y0996   77556       56   59019    music  English  Individual
997     Y0997   65648      139   66299    music  English   Goverment
998     Y0998  139267       36  125546     news  English   Goverment
999     Y0999  169977       13   27183   gaming   Russia  Individual

In [25]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   ChannelID  1000 non-null   object
 1   subs       1000 non-null   int64 
 2   nvideos    1000 non-null   int64 
 3   views      1000 non-null   int64 
 4   Category   1000 non-null   object
 5   Language   1000 non-null   object
 6   Type       1000 non-null   object
dtypes: int64(3), object(4)
memory usage: 54.8+ KB


In [26]:
df1.shape

(1000, 7)

In [27]:
df1.loc[:4]

ChannelID    subs  nvideos   views Category  Language        Type
0     Y0000  120494       71     111     food   Chinese   Goverment
1     Y0001   94610       91   90663     news  Japanese  Individual
2     Y0002  193049       23  222465     food   Chinese   Goverment
3     Y0003   85512        9   86226     news   Chinese         NGO
4     Y0004  158689       12   23830     news    Franch  Individual

In [28]:
needed_cols=['Type','views']
sample=df1.loc[:,needed_cols]
sample

Type   views
0     Goverment     111
1    Individual   90663
2     Goverment  222465
3           NGO   86226
4    Individual   23830
..          ...     ...
995  Individual   63153
996  Individual   59019
997   Goverment   66299
998   Goverment  125546
999  Individual   27183

[1000 rows x 2 columns]

In [29]:
df1.loc[[x for x in range(5,10)],['subs','nvideos']]

subs  nvideos
5  152856       12
6   36372       65
7  131259      130
8  137299       86
9   98378       25

In [30]:
df1.isnull().sum()

ChannelID    0
subs         0
nvideos      0
views        0
Category     0
Language     0
Type         0
dtype: int64

In [31]:
df1['subs'].nunique()

979

In [32]:
df1[(df1['views']>150000) & (df1['subs']>200000)]

ChannelID    subs  nvideos   views Category  Language        Type
18      Y0018  209539       53  242160   gaming   English  Individual
45      Y0045  201164      134  179973     news   Spanish   Corperate
128     Y0128  205131      139  165055    music   English         NGO
242     Y0242  228267      106  221891   travel    Franch  Individual
308     Y0308  245577      198  240306   gaming   Chinese   Corperate
370     Y0370  229787        9  197126   gaming   Spanish   Corperate
393     Y0393  217080       63  244790    music  Japanese   Corperate
412     Y0412  207125       72  279025   gaming   English         NGO
487     Y0487  200504      121  287370   gaming   English   Goverment
668     Y0668  220102       77  158524     food   Spanish   Corperate
671     Y0671  218053      174  169290     food   English  Individual
715     Y0715  213963      126  308525   gaming   English   Goverment
766     Y0766  248037       50  312706   gaming  Japanese  Individual
772     Y0772  213767      126  312646     news    Franch  Individual
797     Y0797  209563      186  192091   travel   English   Goverment

In [33]:
byLanguage=df1.groupby('Language')
byLanguage

In [34]:
byLanguage.mean()

<ipython-input-34-b9813ba23235>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  byLanguage.mean()


subs     nvideos         views
Language                                         
Chinese   106169.964602  100.823009  71538.017699
English    97928.101420  100.417850  75623.034483
Franch     96251.754545  109.263636  74285.863636
Japanese  100079.922330  108.922330  77399.155340
Russia     99113.215054   92.752688  76220.161290
Spanish   110002.375000   87.613636  75900.931818

In [35]:
byLanguage.sum()

<ipython-input-35-4f24ab1cee8d>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  byLanguage.sum()


subs  nvideos     views
Language                             
Chinese   11997206    11393   8083796
English   48278554    49506  37282156
Franch    10587693    12019   8171445
Japanese  10308232    11219   7972113
Russia     9217529     8626   7088475
Spanish    9680209     7710   6679282

In [36]:
byLanguage.sum().sort_values(by=['subs'])

<ipython-input-36-4d320c35c28e>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  byLanguage.sum().sort_values(by=['subs'])


subs  nvideos     views
Language                             
Russia     9217529     8626   7088475
Spanish    9680209     7710   6679282
Japanese  10308232    11219   7972113
Franch    10587693    12019   8171445
Chinese   11997206    11393   8083796
English   48278554    49506  37282156

In [37]:
byLanguage.describe()

subs                                                            \
          count           mean           std      min       25%       50%   
Language                                                                    
Chinese   113.0  106169.964602  47210.303740      1.0  76203.00  102662.0   
English   493.0   97928.101420  48075.582903      1.0  62906.00   96894.0   
Franch    110.0   96251.754545  46025.980692      1.0  66076.25   98274.5   
Japanese  103.0  100079.922330  51372.207857      1.0  68753.50   94553.0   
Russia     93.0   99113.215054  46694.096310      1.0  66795.00   99166.0   
Spanish    88.0  110002.375000  48718.525443  23414.0  74229.75  111233.0   

                             nvideos              ...                views  \
               75%       max   count        mean  ...    75%    max  count   
Language                                          ...                        
Chinese   127896.0  245577.0   113.0  100.823009  ...  156.0  198.0  113.0   
English   130751.0  248170.0   493.0  100.417850  ...  151.0  199.0  493.0   
Franch    124991.0  228267.0   110.0  109.263636  ...  158.5  199.0  110.0   
Japanese  128796.0  248037.0   103.0  108.922330  ...  163.5  199.0  103.0   
Russia    132940.0  182298.0    93.0   92.752688  ...  135.0  196.0   93.0   
Spanish   131957.0  262714.0    88.0   87.613636  ...  138.5  197.0   88.0   

                                                                            \
                  mean           std     min       25%      50%        75%   
Language                                                                     
Chinese   71538.017699  56679.218260    59.0  26181.00  64104.0   96473.00   
English   75623.034483  58913.066575     5.0  27577.00  63549.0  110508.00   
Franch    74285.863636  63394.937166    46.0  22837.00  59844.5   98816.75   
Japanese  77399.155340  63455.051269    39.0  24073.00  71494.0  116650.50   
Russia    76220.161290  60127.361571    14.0  26665.00  63329.0  112426.00   
Spanish   75900.931818  57967.606991  1821.0  28808.75  63670.5  117354.00   

                    
               max  
Language            
Chinese   288063.0  
English   308525.0  
Franch    312646.0  
Japanese  312706.0  
Russia    240519.0  
Spanish   210497.0  

[6 rows x 24 columns]

In [38]:
byLanguage.describe().loc['Category']

KeyError: ignored

In [41]:
df=pd.read_csv('/content/ds_salaries.csv')

In [42]:
df

Unnamed: 0  work_year experience_level employment_type  \
0             0       2020               MI              FT   
1             1       2020               SE              FT   
2             2       2020               SE              FT   
3             3       2020               MI              FT   
4             4       2020               SE              FT   
..          ...        ...              ...             ...   
602         602       2022               SE              FT   
603         603       2022               SE              FT   
604         604       2022               SE              FT   
605         605       2022               SE              FT   
606         606       2022               MI              FT   

                      job_title  salary salary_currency  salary_in_usd  \
0                Data Scientist   70000             EUR          79833   
1    Machine Learning Scientist  260000             USD         260000   
2             Big Data Engineer   85000             GBP         109024   
3          Product Data Analyst   20000             USD          20000   
4     Machine Learning Engineer  150000             USD         150000   
..                          ...     ...             ...            ...   
602               Data Engineer  154000             USD         154000   
603               Data Engineer  126000             USD         126000   
604                Data Analyst  129000             USD         129000   
605                Data Analyst  150000             USD         150000   
606                AI Scientist  200000             USD         200000   

    employee_residence  remote_ratio company_location company_size  
0                   DE             0               DE            L  
1                   JP             0               JP            S  
2                   GB            50               GB            M  
3                   HN             0               HN            S  
4                   US            50               US            L  
..                 ...           ...              ...          ...  
602                 US           100               US            M  
603                 US           100               US            M  
604                 US             0               US            M  
605                 US           100               US            M  
606                 IN           100               US            L  

[607 rows x 12 columns]